/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.18).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.ErrorResponse;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.bind.annotation.CookieValue;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2020-03-21T16:30:27.879Z[GMT]")
@Api(value = "forgotpassword", description = "the forgotpassword API")
public interface ForgotpasswordApi {

    @ApiOperation(value = "Forgot password", nickname = "forgotpasswordPost", notes = "Enables user to give emailid to recieve mail to update password", tags={ "LoginController", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "successfully sent an email to the user"),
        @ApiResponse(code = 400, message = "Bad request", response = ErrorResponse.class),
        @ApiResponse(code = 404, message = "No user exists with given email address", response = ErrorResponse.class),
        @ApiResponse(code = 417, message = "Email format is wrong", response = ErrorResponse.class),
        @ApiResponse(code = 200, message = "Unexpected error") })
    @RequestMapping(value = "/forgotpassword",
        produces = { "application/json" }, 
        method = RequestMethod.POST)
    ResponseEntity<Void> forgotpasswordPost(@DecimalMin("1")@ApiParam(value = "The email ID of the user to recieve password update mail.",required=true) @PathVariable("email") String email
);

}
