/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.18).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.annotations.*;
import io.swagger.model.ErrorResponse;
import io.swagger.model.User;
import io.swagger.model.UserDto;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import javax.validation.Valid;
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2020-03-21T16:30:27.879Z[GMT]")
@CrossOrigin(origins = "http://localhost:8082", maxAge = 3600)
@Api(value = "users", description = "the users API")
@RequestMapping(value = "/users/")
public interface UsersApi {

    @ApiOperation(value = "Create a new user", nickname = "usersPost", notes = "Api to return user having given id", tags={ "UserController", })
    @ApiResponses(value = { 
        @ApiResponse(code = 201, message = "Created"),
        @ApiResponse(code = 405, message = "Invalid input", response = ErrorResponse.class) })
    @PostMapping
    ResponseEntity<?> usersPost(@ApiParam(value = "" ,required=true )  @Valid @RequestBody UserDto body
);

}
